import { Tenant, Apartment } from './types';

const floors = [
  { key: 'السرداب', label: 'السرداب', prefix: '0' },
  { key: 'الأرضي', label: 'الأرضي', prefix: '0' },
  { key: 'الأول', label: 'الأول', prefix: '1' },
  { key: 'الثاني', label: 'الثاني', prefix: '2' },
  { key: 'الثالث', label: 'الثالث', prefix: '3' },
  { key: 'الرابع', label: 'الرابع', prefix: '4' },
  { key: 'الخامس', label: 'الخامس', prefix: '5' },
  { key: 'السادس', label: 'السادس', prefix: '6' },
  { key: 'السابع', label: 'السابع', prefix: '7' },
];

export { floors };

export const initialApartments: Apartment[] = [
  { id: 'apt-basement', number: 'السرداب', floor: 'السرداب', status: 'occupied', tenantId: 't1', rentAmount: 450 },
  { id: 'apt-shop', number: 'المحل', floor: 'الأرضي', status: 'occupied', tenantId: 't2', rentAmount: 575 },
  { id: 'apt-002', number: '002', floor: 'الأرضي', status: 'occupied', tenantId: 't3', rentAmount: 200 },
  { id: 'apt-001', number: '001', floor: 'الأرضي', status: 'occupied', tenantId: 't30', rentAmount: 130 },
  { id: 'apt-003', number: '003', floor: 'الأرضي', status: 'occupied', tenantId: 't35', rentAmount: 125 },
  { id: 'apt-101', number: '101', floor: 'الأول', status: 'occupied', tenantId: 't4', rentAmount: 130 },
  { id: 'apt-102', number: '102', floor: 'الأول', status: 'occupied', tenantId: 't5', rentAmount: 130 },
  { id: 'apt-103', number: '103', floor: 'الأول', status: 'occupied', tenantId: 't20', rentAmount: 140 },
  { id: 'apt-104', number: '104', floor: 'الأول', status: 'occupied', tenantId: 't38', rentAmount: 140 },
  { id: 'apt-105', number: '105', floor: 'الأول', status: 'occupied', tenantId: 't24', rentAmount: 140 },
  { id: 'apt-106', number: '106', floor: 'الأول', status: 'occupied', tenantId: 't6', rentAmount: 145 },
  { id: 'apt-107', number: '107', floor: 'الأول', status: 'occupied', tenantId: 't7', rentAmount: 250 },
  { id: 'apt-201', number: '201', floor: 'الثاني', status: 'occupied', tenantId: 't29', rentAmount: 130 },
  { id: 'apt-203', number: '203', floor: 'الثاني', status: 'occupied', tenantId: 't28', rentAmount: 150 },
  { id: 'apt-204', number: '204', floor: 'الثاني', status: 'occupied', tenantId: 't8', rentAmount: 260 },
  { id: 'apt-205', number: '205', floor: 'الثاني', status: 'occupied', tenantId: 't9', rentAmount: 265 },
  { id: 'apt-301', number: '301', floor: 'الثالث', status: 'occupied', tenantId: 't32', rentAmount: 130 },
  { id: 'apt-302', number: '302', floor: 'الثالث', status: 'occupied', tenantId: 't37', rentAmount: 130 },
  { id: 'apt-303', number: '303', floor: 'الثالث', status: 'occupied', tenantId: 't40', rentAmount: 160 },
  { id: 'apt-304', number: '304', floor: 'الثالث', status: 'occupied', tenantId: 't33', rentAmount: 140 },
  { id: 'apt-305', number: '305', floor: 'الثالث', status: 'occupied', tenantId: 't21', rentAmount: 140 },
  { id: 'apt-306', number: '306', floor: 'الثالث', status: 'occupied', tenantId: 't36', rentAmount: 140 },
  { id: 'apt-307', number: '307', floor: 'الثالث', status: 'occupied', tenantId: 't22', rentAmount: 130 },
  { id: 'apt-308', number: '308', floor: 'الثالث', status: 'occupied', tenantId: 't26', rentAmount: 140 },
  { id: 'apt-309', number: '309', floor: 'الثالث', status: 'occupied', tenantId: 't31', rentAmount: 140 },
  { id: 'apt-310', number: '310', floor: 'الثالث', status: 'occupied', tenantId: 't10', rentAmount: 130 },
  { id: 'apt-401', number: '401', floor: 'الرابع', status: 'occupied', tenantId: 't11', rentAmount: 175 },
  { id: 'apt-402', number: '402', floor: 'الرابع', status: 'occupied', tenantId: 't12', rentAmount: 260 },
  { id: 'apt-403', number: '403', floor: 'الرابع', status: 'occupied', tenantId: 't13', rentAmount: 260 },
  { id: 'apt-501', number: '501', floor: 'الخامس', status: 'occupied', tenantId: 't14', rentAmount: 170 },
  { id: 'apt-502', number: '502', floor: 'الخامس', status: 'occupied', tenantId: 't39', rentAmount: 150 },
  { id: 'apt-503', number: '503', floor: 'الخامس', status: 'occupied', tenantId: 't15', rentAmount: 265 },
  { id: 'apt-504', number: '504', floor: 'الخامس', status: 'occupied', tenantId: 't41', rentAmount: 150 },
  { id: 'apt-505', number: '505', floor: 'الخامس', status: 'occupied', tenantId: 't42', rentAmount: 150 },
  { id: 'apt-506', number: '506', floor: 'الخامس', status: 'occupied', tenantId: 't43', rentAmount: 150 },
  { id: 'apt-601', number: '601', floor: 'السادس', status: 'occupied', tenantId: 't16', rentAmount: 185 },
  { id: 'apt-602', number: '602', floor: 'السادس', status: 'occupied', tenantId: 't17', rentAmount: 260 },
  { id: 'apt-607', number: '607', floor: 'السادس', status: 'occupied', tenantId: 't34', rentAmount: 130 },
  { id: 'apt-608', number: '608', floor: 'السادس', status: 'occupied', tenantId: 't23', rentAmount: 140 },
  { id: 'apt-609', number: '609', floor: 'السادس', status: 'occupied', tenantId: 't18', rentAmount: 140 },
  { id: 'apt-610', number: '610', floor: 'السادس', status: 'occupied', tenantId: 't25', rentAmount: 140 },
  { id: 'apt-701', number: '701', floor: 'السابع', status: 'occupied', tenantId: 't27', rentAmount: 140 },
  { id: 'apt-702', number: '702', floor: 'السابع', status: 'occupied', tenantId: 't19', rentAmount: 125 },
];

export const initialTenants: Tenant[] = [
  { id: 't1', name: 'خالد عبدالحميد الصباغ', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-basement', floor: 'السرداب', rentAmount: 450, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: 'نقدا', registrationDate: '2024-01-13' },
  { id: 't2', name: 'رفيق الإسلام محمد علي', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-shop', floor: 'الأرضي', rentAmount: 575, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: 'نقدا', registrationDate: '2024-01-06' },
  { id: 't3', name: 'محمد أنور جلال الدين', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-002', floor: 'الأرضي', rentAmount: 200, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: 'نقدا', registrationDate: '2024-01-06' },
  { id: 't4', name: 'محمد جان علم', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-101', floor: 'الأول', rentAmount: 130, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: 'نقدا', registrationDate: '2024-01-06' },
  { id: 't5', name: 'محمد جاكر حسين', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-102', floor: 'الأول', rentAmount: 130, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: 'نقدا', registrationDate: '2024-01-06' },
  { id: 't6', name: 'عمر سارفراز ميرزا', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-106', floor: 'الأول', rentAmount: 145, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: 'نقدا', registrationDate: '2024-01-06' },
  { id: 't7', name: 'مصطفى كمال قطب', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-107', floor: 'الأول', rentAmount: 250, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: 'نقدا', registrationDate: '2024-01-06' },
  { id: 't8', name: 'ايسيدور ديسوزا لويس', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-204', floor: 'الثاني', rentAmount: 260, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: 'نقدا', registrationDate: '2024-01-06' },
  { id: 't9', name: 'اندو انورادها ديلو كشي', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-205', floor: 'الثاني', rentAmount: 265, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: 'نقدا', registrationDate: '2024-01-06' },
  { id: 't10', name: 'عبدالله سعد عرابي', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-310', floor: 'الثالث', rentAmount: 130, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: 'نقدا', registrationDate: '2024-01-06' },
  { id: 't11', name: 'أنور الدين عمر', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-401', floor: 'الرابع', rentAmount: 175, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: 'نقدا', registrationDate: '2024-01-06' },
  { id: 't12', name: 'موسى محمود حمدان', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-402', floor: 'الرابع', rentAmount: 260, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: 'نقدا', registrationDate: '2024-01-06' },
  { id: 't13', name: 'مراد احمد محمد', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-403', floor: 'الرابع', rentAmount: 260, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: 'نقدا', registrationDate: '2024-01-06' },
  { id: 't14', name: 'توني انطوني', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-501', floor: 'الخامس', rentAmount: 170, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: 'نقدا', registrationDate: '2024-01-06' },
  { id: 't15', name: 'وكيل احمد شفيق', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-503', floor: 'الخامس', rentAmount: 265, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: 'نقدا', registrationDate: '2024-01-06' },
  { id: 't16', name: 'سريجيث بوناتيل', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-601', floor: 'السادس', rentAmount: 185, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: 'نقدا', registrationDate: '2024-01-06' },
  { id: 't17', name: 'إبراهيم عبدالرحمن البرم', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-602', floor: 'السادس', rentAmount: 260, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: 'نقدا', registrationDate: '2024-01-06' },
  { id: 't18', name: 'ريسام روى فيلوستاس جاميلا', civilId: '269121403975', nationality: 'فلبيني', profession: 'فني تركيب اسنان', phone: '66726098', apartmentId: 'apt-609', floor: 'السادس', rentAmount: 140, leaseStart: '2024-02-01', leaseEnd: '2025-01-31', leaseDuration: 'سنة', paymentMethod: 'نقدا', registrationDate: '2024-01-06' },
  { id: 't19', name: 'ارنيست ايناسكوتي', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-702', floor: 'السابع', rentAmount: 125, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: 'نقدا', registrationDate: '2024-01-06' },
  { id: 't20', name: 'برونوب كانتي ناث', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-103', floor: 'الأول', rentAmount: 140, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: '', registrationDate: '2024-04-03' },
  { id: 't21', name: 'محمود احمد علي حسين', civilId: '295050704613', nationality: 'مصري', profession: 'شركة دعيج السلمان', phone: '69039017', apartmentId: 'apt-305', floor: 'الثالث', rentAmount: 140, leaseStart: '2024-07-01', leaseEnd: '2025-06-30', leaseDuration: 'سنة', paymentMethod: '', registrationDate: '2024-06-16' },
  { id: 't22', name: 'جراسيلدا لاورون بالويت', civilId: '271062902653', nationality: 'فلبيني', profession: 'شركة النسائم لمواد التجميل', phone: '55242537', apartmentId: 'apt-307', floor: 'الثالث', rentAmount: 130, leaseStart: '2024-06-01', leaseEnd: '2025-05-31', leaseDuration: 'سنة', paymentMethod: '', registrationDate: '2024-06-01' },
  { id: 't23', name: 'إيهاب حسين علي سلام', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-608', floor: 'السادس', rentAmount: 140, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: '', registrationDate: '2024-08-19' },
  { id: 't24', name: 'موسى فرج القطيفان', civilId: '280052501834', nationality: 'سوري', profession: 'مركز بيت المستقبل لمواد الديكور', phone: '60935400', apartmentId: 'apt-105', floor: 'الأول', rentAmount: 140, leaseStart: '2024-09-01', leaseEnd: '2025-08-31', leaseDuration: 'سنة', paymentMethod: '', registrationDate: '2024-08-20' },
  { id: 't25', name: 'بدر شحاته إبراهيم حسن', civilId: '290010134318', nationality: 'مصري', profession: 'مفتش صحي', phone: '96650561', apartmentId: 'apt-610', floor: 'السادس', rentAmount: 140, leaseStart: '2024-09-01', leaseEnd: '2025-08-31', leaseDuration: 'سنة', paymentMethod: '', registrationDate: '2024-08-28' },
  { id: 't26', name: 'طاهر مصطفى عبدالغني مصطفى', civilId: '293092005803', nationality: 'مصري', profession: 'كاتب شؤون موظفين', phone: '60748190', apartmentId: 'apt-308', floor: 'الثالث', rentAmount: 140, leaseStart: '2024-11-13', leaseEnd: '2024-11-12', leaseDuration: 'سنة', paymentMethod: '', registrationDate: '2024-11-13' },
  { id: 't27', name: 'نور الدين سولج ناملا', civilId: '', nationality: 'فلبيني', profession: '', phone: '', apartmentId: 'apt-701', floor: 'السابع', rentAmount: 140, leaseStart: '2024-12-01', leaseEnd: '2025-11-30', leaseDuration: 'سنة', paymentMethod: '', registrationDate: '2024-12-06' },
  { id: 't28', name: 'نور سويندر انبيلاي ليلا', civilId: '284052709641', nationality: 'هندي', profession: 'كاشير جمعية ابوفطيرة التعاونية', phone: '', apartmentId: 'apt-203', floor: 'الثاني', rentAmount: 150, leaseStart: '2025-01-01', leaseEnd: '2025-12-31', leaseDuration: 'سنة', paymentMethod: '', registrationDate: '2024-12-29' },
  { id: 't29', name: 'سانيدو بريهاني زيودي', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-201', floor: 'الثاني', rentAmount: 130, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: '', registrationDate: '2025-03-02' },
  { id: 't30', name: 'علي محمد كرم', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-001', floor: 'الأرضي', rentAmount: 130, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: '', registrationDate: '2025-03-02' },
  { id: 't31', name: 'محمد شعبان عز الدين محمد', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-309', floor: 'الثالث', rentAmount: 140, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: '', registrationDate: '2025-03-02' },
  { id: 't32', name: 'بيزوايهو ينجيداو اليمو', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-301', floor: 'الثالث', rentAmount: 130, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: '', registrationDate: '2025-06-11' },
  { id: 't33', name: 'فادي منصور بلوط', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-304', floor: 'الثالث', rentAmount: 140, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: '', registrationDate: '2025-06-11' },
  { id: 't34', name: 'إبراهيم عبدالسلام محمود سباق', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-607', floor: 'السادس', rentAmount: 130, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: '', registrationDate: '2025-11-17' },
  { id: 't35', name: 'سوجيت ريجال', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-003', floor: 'الأرضي', rentAmount: 125, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: '', registrationDate: '2025-11-29' },
  { id: 't36', name: 'محمد حفيظ الرحمن محمد صراط الله', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-306', floor: 'الثالث', rentAmount: 140, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: '', registrationDate: '2026-03-05' },
  { id: 't37', name: 'ريحانه سيد', civilId: '', nationality: '', profession: '', phone: '', apartmentId: 'apt-302', floor: 'الثالث', rentAmount: 130, leaseStart: '', leaseEnd: '', leaseDuration: '', paymentMethod: '', registrationDate: '2026-06-10' },
  { id: 't38', name: 'فتحي سعداوي حسن منصور', civilId: '264021602114', nationality: 'مصري', profession: 'ممرض الهيئة العامة لشئون ذوي الإعاقة', phone: '99982450', apartmentId: 'apt-104', floor: 'الأول', rentAmount: 140, leaseStart: '2026-07-27', leaseEnd: '2027-07-26', leaseDuration: 'سنة', paymentMethod: '', registrationDate: '2026-08-03' },
  { id: 't39', name: 'فاسيول مولا محمد زهير الحق', civilId: '283102011053', nationality: 'بنغلاديشي', profession: 'شركة سحاب للأبواب والشبابيك الجاهزة', phone: '95589657', apartmentId: 'apt-502', floor: 'الخامس', rentAmount: 150, leaseStart: '2026-07-26', leaseEnd: '2027-07-25', leaseDuration: 'سنة', paymentMethod: '', registrationDate: '2026-08-03' },
  { id: 't40', name: 'أبو الحسين عبد المنان', civilId: '270082402491', nationality: 'بنغلاديشي', profession: 'شركة محمد صالح ورضا يوسف بهبهاني', phone: '60427512', apartmentId: 'apt-303', floor: 'الثالث', rentAmount: 160, leaseStart: '2026-07-27', leaseEnd: '2027-07-26', leaseDuration: 'سنة', paymentMethod: '', registrationDate: '2026-08-03' },
  { id: 't41', name: 'ام دي عبدالرب ام دي عبدالاول', civilId: '282010133227', nationality: 'بنغلاديشي', profession: 'شركة محمد حمود الشايع', phone: '55442161', apartmentId: 'apt-504', floor: 'الخامس', rentAmount: 150, leaseStart: '2026-07-25', leaseEnd: '2027-07-23', leaseDuration: 'سنة', paymentMethod: '', registrationDate: '2026-08-03' },
  { id: 't42', name: 'محمد مونول حسين محمد', civilId: '282100104868', nationality: 'بنغلاديشي', profession: 'شركة يونايتد تريدرس للتجارة العامة والمقاولات', phone: '51609070', apartmentId: 'apt-505', floor: 'الخامس', rentAmount: 150, leaseStart: '2026-07-26', leaseEnd: '2027-07-25', leaseDuration: 'سنة', paymentMethod: '', registrationDate: '2026-08-03' },
  { id: 't43', name: 'محمد عبدول محمد عبدول اوال وازيد', civilId: '290010157368', nationality: 'بنغلاديشي', profession: 'شركة سحاب للابواب والشبابيك الجاهزة', phone: '51639811', apartmentId: 'apt-506', floor: 'الخامس', rentAmount: 150, leaseStart: '2026-07-22', leaseEnd: '2027-07-21', leaseDuration: 'سنة', paymentMethod: '', registrationDate: '2026-08-03' },
];
